### ISSUE TITLE
ES6 + React

### ISSUE THREAD

**Issue by zsherman** [cassiozen/ReactCasts#19]
There are a lot of cool new capabilities that es6 brings which compliment react nicely, spreading properties via `{...props}` for example. Other things that might be worth mentioning or exploring:

- decorators
- classes & class methods
- destructuring args
- {...rest} 😁

**Comment by cassiozen** [comment]
Hi @zsherman - an update on this:

Looks like ES6 is commonplace now (specially because of tools like create-react-app), so a screencast now wouldn't be that useful. 

I'll close this issue, but if you have a different opinion, please feel free to reopen so we can keep the conversation going. 

Again, thanks for the suggestion, please don't feel discouraged to make further suggestions in the future because this one wasn't used.
