### ISSUE TITLE
React in Production / Large App Overview

### ISSUE THREAD

**Issue by aconanlai** [cassiozen/ReactCasts#22]
Would be cool to see a review of a larger app, tools/libraries used, conventions, etc - could maybe show adding process of adding a new feature to the app.

**Comment by cassiozen** [comment]
Hi @aconanlai. I feel that this topic would be too big for a 15-minute video. I'll close the issue for now, but please feel free to reopen it if you'd like to further discuss the issue.

Again, thanks for the suggestion, please don't feel discouraged to make further suggestions in the future because this one wasn't used.
