### ISSUE TITLE
Where to put business logic

### ISSUE THREAD

**Issue by slig** [cassiozen/ReactCasts#30]
[This article](https://medium.com/@jeffbski/where-do-i-put-my-business-logic-in-a-react-redux-application-9253ef91ce1) provides some nice arguments for each approach, but I think it'd be nice to have a screencast about it. Thanks!

**Comment by iyn** [comment]
I would love to watch a ReactCasts episode that explores this topic!

I've been using `redux-logic` since it was announced and so far it works quite good in my (pre-production) project, definitely worth checking out. The article itself is also very good at describing the basics of all common approaches to side effects/business logic.
