### ISSUE TITLE
Implement social login using Passport in react app powered by React-router.

### ISSUE THREAD

**Issue by arshdkhn1** [cassiozen/ReactCasts#32]
Implementing social login while using node.js and server side routing is quite easy but implementing it with react-router and safely bypass all the security issues is a mess. Please try to record this cast asap.

Thank you very much.

**Comment by cassiozen** [comment]
Cool, thanks for the suggestion. Any reference materials you are aware of?

**Comment by arshdkhn1** [comment]
@cassiozen  https://github.com/arshdkhn1/react-router/tree/master/examples/auth-flow I have seen some jwt example on web but donno how they work atm. What I have done in some apps is to declare auth routes handler before catch*all  route handler for react-router. I want to see how social logic and both local passport strategies can be implemented. It will be really verry helpful if you make some react-casts about this topic.

**Comment by cassiozen** [comment]
I'll close this issue because the subject is a little too big for a 15-minute video, but if you have a different opinion, please feel free to reopen so we can keep the conversation going. 

Again, thanks for the suggestion, please don't feel discouraged to make further suggestions in the future because this one wasn't used.
